version: '3'

volumes:
  mysql_data:
  
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    env_file: development.env

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_data:/var/lib/mysql'
    env_file: development.env
    ports:
      - '3306:3306'


